_BASE_: ../Base-bagtricks.yml

MODEL:
  BACKBONE:
    DEPTH: 101x
    WITH_IBN: True

DATASETS:
  NAMES: ("Aicity",)
  TESTS: ("Aicity",)

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 128

INPUT:
  SIZE_TRAIN: [ 256, 256 ]
  SIZE_TEST: [ 256, 256 ]

OUTPUT_DIR: logs/aicity/bagtricks_R101-ibn
